"""Rendered-Helm-YAML snapshot drift gate for the AgentOS chart (Sprint 14B-Z1a).

Mirrors the well-known-schema snapshot convention: `helm template` output with a
pinned release name / namespace / values file is byte-compared to a committed
snapshot. Drift fails the gate with the exact regeneration command.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[3]
_CHART_DIR = _REPO_ROOT / "infra" / "charts" / "agentos"
_CI = _CHART_DIR / "ci"
_SNAPSHOT_VALUES = _CI / "snapshot-values.yaml"
_HELM_DIR = Path(__file__).resolve().parent / "helm"
_SNAPSHOT = _HELM_DIR / "agentos_rendered.yaml"

# (default + the three Z1b-a opt-in scenarios; each layered over the base values)
_SCENARIOS = [
    pytest.param([_SNAPSHOT_VALUES], _SNAPSHOT, id="default"),
    pytest.param(
        [_SNAPSHOT_VALUES, _CI / "snapshot-values-ingress.yaml"],
        _HELM_DIR / "agentos_rendered_ingress.yaml",
        id="ingress",
    ),
    pytest.param(
        [_SNAPSHOT_VALUES, _CI / "snapshot-values-route.yaml"],
        _HELM_DIR / "agentos_rendered_route.yaml",
        id="route",
    ),
    pytest.param(
        [_SNAPSHOT_VALUES, _CI / "snapshot-values-servicemonitor.yaml"],
        _HELM_DIR / "agentos_rendered_servicemonitor.yaml",
        id="servicemonitor",
    ),
    pytest.param(
        [_SNAPSHOT_VALUES, _CI / "snapshot-values-externalsecret.yaml"],
        _HELM_DIR / "agentos_rendered_externalsecret.yaml",
        id="externalsecret",
    ),
    pytest.param(
        [_SNAPSHOT_VALUES, _CI / "snapshot-values-otel-http.yaml"],
        _HELM_DIR / "agentos_rendered_otel-http.yaml",
        id="otel-http",
    ),
]

# The committed snapshot is byte-generated by the pinned primary renderer, Helm
# v4.2.2 — the version the CI `helm-chart` job installs (and the local Homebrew
# stack). A different Helm version renders byte-differently (label ordering,
# resource sort), so this byte-equality gate runs ONLY under that version. CI's
# AUTHORITATIVE snapshot drift gate is the pinned-Helm-4 `helm-chart` workflow
# job (`.github/workflows/python.yml`); this pytest test is the local-dev
# convenience that catches drift before push. GitHub's `ubuntu-latest` runner
# ships a pre-installed helm of a different version, so the unpinned `lint +
# test` job must skip this — the `helm-chart` job is the real gate there.
_SNAPSHOT_HELM_VERSION = "v4.2.2"


def _helm_matches_snapshot_version() -> bool:
    if shutil.which("helm") is None:
        return False
    out = subprocess.run(
        ["helm", "version", "--short"],
        capture_output=True,
        text=True,
        check=False,
    ).stdout.strip()
    return out.startswith(_SNAPSHOT_HELM_VERSION)


def _render(values_files: list[Path]) -> str:
    cmd = ["helm", "template", "rel", str(_CHART_DIR), "--namespace", "cognic"]
    for vf in values_files:
        cmd += ["-f", str(vf)]
    raw = subprocess.run(cmd, capture_output=True, text=True, check=True).stdout
    # `helm template` ends its combined output with a trailing blank line; normalize
    # to exactly one final newline so the committed snapshot is git-clean.
    return raw.rstrip("\n") + "\n"


@pytest.mark.skipif(
    not _helm_matches_snapshot_version(),
    reason=f"byte-snapshot is generated by Helm {_SNAPSHOT_HELM_VERSION}; "
    "the pinned-Helm-4 CI `helm-chart` job is the authoritative drift gate",
)
@pytest.mark.parametrize(("values_files", "snapshot"), _SCENARIOS)
def test_rendered_chart_matches_snapshot(values_files: list[Path], snapshot: Path) -> None:
    rendered = _render(values_files)
    if not snapshot.exists():
        snapshot.parent.mkdir(parents=True, exist_ok=True)
        snapshot.write_text(rendered)
        pytest.fail(f"snapshot created at {snapshot} — review and commit it, then re-run")
    assert rendered == snapshot.read_text(), (
        f"rendered chart drifted from {snapshot}. If the drift is intentional, "
        f"regenerate via `rm {snapshot} && uv run pytest "
        f"tests/unit/infra/test_helm_chart.py::test_rendered_chart_matches_snapshot -x` "
        f"then commit the new snapshot."
    )


@pytest.mark.skipif(shutil.which("helm") is None, reason="helm not on PATH")
def test_chart_lints_clean() -> None:
    result = subprocess.run(
        ["helm", "lint", str(_CHART_DIR), "-f", str(_SNAPSHOT_VALUES)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, f"helm lint failed:\n{result.stdout}\n{result.stderr}"
